# Site settings
title: vipulkrsingh
description: >
  Burp's of randomness, arising out of work, love, life and beyound.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vipulkrsingh.github.io" # the base hostname & protocol for your site

author:
  fullname: Vipul Kumar singh
  googleplus: https://plus.google.com/u/0/100222356978656072971
  github: vipulkrsingh
  twitter: vipulkrsingh
  disqus: vipulkrsingh

google_analytics: 'UA-70796469-1'

# Build settings
markdown: kramdown
