# Site settings
title: burp
description: >
  Burp's of randomness, arising out of work, love, life and beyound.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Vipul Kumar singh
  googleplus: https://plus.google.com/u/0/100222356978656072971
  github: vipulkrsingh
  twitter: vipulkrsingh
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
