# Site Settings
title: Margin Overflow
description: "Where code meets contemplation" # Optional tagline suggestion
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vipulkrsingh.github.io" # your site's domain

# Build Settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 5


# Theme settings
remote_theme: chesterhow/tale

# Plugin settings
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Author settings
author:
  name: Vipul Kumar Singh
  github: vipulkrsingh
  twitter: vipulkrsingh
  email: vipulkrsingh@gmail.com
  linkedin: vipul-kumar-singh-792b02a
  bio: Programmer, Engineer .. Student of the force!

# SEO settings
twitter:
  username: vipulkrsingh
  card: summary_large_image

social:
  name: Vipul Kumar Singh
  links:
    - https://twitter.com/vipulkrsingh
    - https://github.com/vipulkrsingh
    - https://linkedin.com/in/vipulkrsingh

# Feed settings
feed:
  path: feed.xml


# Layout settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
